config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # config/routes.rb

  resources :games, only: [:create] do
    member do
      get 'next_match', to: 'games#next_match'
    end
    resources :matches do
      get 'results', on: :member
    end
  end


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user

  has_many :matches, dependent: :destroy
  # validate :has_exactly_five_matches

  after_create :generate_matches

  private

  def has_exactly_five_matches
    errors.add(:matches, "doit avoir exactement 5 parties") unless matches.size == 5
  end

  def generate_matches
    voyelles = %w[a e i o u y]
    consonnes = %w[b c d f g h j k l m n p q r s t v w x z]

    5.times do
      tirage = (voyelles.sample(5) + consonnes.sample(5)).shuffle.join
      matches.create!(
        ten_letters_list: tirage,
        word: '', # Ce champ devrait être mis à jour avec un mot valide selon vos règles
        available: true
      )
    end
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :game
  has_many :solutions, dependent: :destroy

  # validates :word, presence: true

  def self.top_words(ten_letters_list)
    word_list_path = Rails.root.join('app', 'assets', 'words.txt')
    valid_word_list = File.read(word_list_path).split("\n").map(&:downcase)
    valid_word_list.select { |word| in_grid?(word, ten_letters_list.upcase.chars) }.sort_by(&:length).reverse.first(10)
  end

  def self.in_grid?(attempt, grid)
    attempt = attempt.upcase.chars
    attempt.all? { |char| grid.include?(char) } && attempt.all? { |char| grid.count(char) >= attempt.count(char) }
  end

end

app/models/solution.rb
class Solution < ApplicationRecord
  belongs_to :match
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :games, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/games_controller.rb
# app/controllers/games_controller.rb
class GamesController < ApplicationController
  # before_action :authenticate_user!

  def create

    game = current_user.games.new(actual_score: 0)

    game.save!

    redirect_to game_match_path(game, game.matches.first)

  end

  def next_match
    game = current_user.games.last
    @next_match = game.matches.find_by(word: '') # Trouve le premier match avec word vide

    if @next_match
      redirect_to game_match_path(game, @next_match)
    else
      redirect_to root_path # Redirige vers la page d'accueil si aucun match n'a word vide
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def show
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    word = match_params.values.first
    grid = @match.ten_letters_list.upcase.chars
    # Vérifiez si le mot est dans la grille et peut être formé
    valid_word = in_grid?(word, grid)

    # Vérifiez si le mot est dans la liste de mots valide
    word_list_path = Rails.root.join('app', 'assets', 'words.txt')
    valid_word_list = File.read(word_list_path).split("\n").map(&:downcase)

    valid_word = valid_word && valid_word_list.include?(word.downcase)

    if valid_word
      @match.word = word
      @match.game.actual_score += word.length
      current_user.best_score = @match.game.actual_score if @match.game.actual_score > current_user.best_score

      if @match.save && @match.game.save && current_user.save
        redirect_to results_game_match_path(@match)
      else
        render :edit
      end
    else
      flash[:alert] = "Le mot n'est pas valide."
      render :show, status: :unprocessable_entity
    end
  end

  def results
    @match = Match.find(params[:id])
    @top_words = Match.top_words(@match.ten_letters_list)
  end

  private

  def match_params
    params.require(:match).permit(:word)
  end

  def in_grid?(attempt, grid)
    attempt = attempt.upcase.chars
    attempt.all? { |char| grid.include?(char) } && attempt.all? { |char| grid.count(char) >= attempt.count(char) }
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LongestWordGaw</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/matches/results.html.erb
<div class="container">
  <div class="bg-white m-3 p-3">
    <div>
      <div>
        <p>Nombre de games : <%= current_user.games.count %></p>
        <p>Meilleur score : <%= current_user.best_score %></p>
      </div>
      <div>
        <p>Nombre de parties jouées : <%= current_user.games.last.matches.where.not(word: '').count %>/5</p>
        <p>Score : <%= current_user.games.last.actual_score %></p>
      </div>
    </div>
  </div>


  <div class="mt-5">
    <div class="row justify-content-center mb-3">
      <% @match.ten_letters_list.chars.each_slice(5) do |slice| %>
        <div class="col-12">
          <div class="d-flex justify-content-between">
            <% slice.each do |letter| %>
              <div class="p-2">
                <div class="letter-tile">
                  <%= letter.upcase %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container bg-white my-5">
    <strong>Mon mot</strong>
    <h2 class="text-center text-primary"><%= @match.word %></h2>
  </div>

  <div class="container bg-white my-5">
    <h3 class="text-primary text-center">Les 10 meilleures réponses</h3>
    <div class="row">
      <div class="col-md-6">
        <ul class="list-unstyled text-center">
          <% @top_words.each_with_index do |word, index| %>
            <% if index < 5 %>
              <li><strong><%= word %></strong></li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="col-md-6">
        <ul class="list-unstyled text-center">
          <% @top_words.each_with_index do |word, index| %>
            <% if index >= 5 %>
              <li><strong><%= word %></strong></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>



  <div class="container m-3 p-3">
    <div class="col-12">
      <%= link_to "Match suivant", next_match_game_path(current_user.games.last), class: "btn btn-primary" %>
    </div>
  </div>


</div>

app/views/matches/show.html.erb
<!-- Assurez-vous d'inclure le CSS de Bootstrap dans votre layout pour que ce code fonctionne -->

<div class="container my-5">
  <div class="row justify-content-center mb-3">
    <% @match.ten_letters_list.chars.each_slice(5) do |slice| %>
      <div class="col-12">
        <div class="d-flex justify-content-between">
          <% slice.each do |letter| %>
            <div class="p-2">
              <div class="letter-tile">
                <%= letter.upcase %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= simple_form_for [:game, @match], url: game_match_path(@match.game, @match), method: :patch do |f| %>
    <div class="row justify-content-center">
      <div class="col-12">
        <%= f.input :word, as: :string, input_html: { class: 'form-control text-left mb-3', placeholder: 'Ton mot le plus long' } %>
      </div>
    </div>
    <%= f.button :submit, class: 'btn btn-primary', value: 'Soumettre le mot' %>
  <% end %>

</div>

app/views/pages/home.html.erb
<div class="container m-3 p-3">
  <div class="col-12">
    <%= form_with url: games_path, method: :post do |form| %>
      <%= form.submit "Nouveau jeu", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      ACCUEIL
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/gwittebolle", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>